#!/bin/sh
#
# $FreeBSD: head/news/nzbget/files/nzbget.in 387515 2015-05-26 22:32:22Z madpilot $
#
# PROVIDE: nzbget
# REQUIRE: DAEMON
# KEYWORD: shutdown
#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# nzbget_enable (bool):	Set to NO by default.
#			Set it to YES to enable it.

. /etc/rc.subr

name=nzbget
rcvar=nzbget_enable

load_rc_config ${name}

: ${nzbget_enable:=NO}
: ${nzbget_user:="_sabnzbd"}

start_cmd="${name}_start"
status_cmd="${name}_status"
stop_cmd="${name}_stop"
command=/usr/local/bin/nzbget

nzbget_start()
{
	echo "Starting ${name}."
	# artificial sleep because it doesnt want to start
	# after a restart without it
	sleep .5
	${command} -D
}

nzbget_stop()
{
	echo "Stopping ${name}."
	${command} -Q
	# artificial sleep because stop is backgrounded
	sleep 3
}

nzbget_status()
{
   ${command} -L S
}

run_rc_command "$1"
